package com.example.tizona.screen;

import org.vaadin.jouni.animator.AnimatorProxy;

import com.example.tizona.common.StringsContainer;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.Sizeable;
import com.vaadin.terminal.gwt.client.ui.AlignmentInfo.Bits;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.Component;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.VerticalSplitPanel;

public class MainScreen extends CustomComponent {

    @AutoGenerated
    private AbsoluteLayout mainLayout;

    @AutoGenerated
    private VerticalSplitPanel verticalSplitPanelPrincipal;

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    // Common objects
    private AnimatorProxy proxy = new AnimatorProxy();

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     * 
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */
    public MainScreen() {
	buildMainLayout();
	setCompositionRoot(mainLayout);

	// Initialize the "effects proxy"
	mainLayout.addComponent(proxy);
	
	verticalSplitPanelPrincipal.setLocked(true);
	verticalSplitPanelPrincipal.setSplitPosition(50,
                Sizeable.UNITS_PIXELS);

	verticalSplitPanelPrincipal.setFirstComponent(hazCabecera());
	
//	Label labelHolaMundo = new Label("hola mundo");
//	mainLayout.addComponent(labelHolaMundo);
//	proxy.animate(labelHolaMundo, AnimType.FADE_IN).setDuration(500).setDelay(0);
    }

    @AutoGenerated
    private AbsoluteLayout buildMainLayout() {
	// common part: create layout
	mainLayout = new AbsoluteLayout();
	mainLayout.setImmediate(false);
	mainLayout.setWidth("100%");
	mainLayout.setHeight("100%");
	mainLayout.setMargin(false);
	
	// top-level component properties
	setWidth("100.0%");
	setHeight("100.0%");
	
	// verticalSplitPanelPrincipal
	verticalSplitPanelPrincipal = new VerticalSplitPanel();
	verticalSplitPanelPrincipal.setImmediate(false);
	verticalSplitPanelPrincipal.setWidth("100.0%");
	verticalSplitPanelPrincipal.setHeight("100.0%");
	verticalSplitPanelPrincipal.setMargin(false);
	mainLayout.addComponent(verticalSplitPanelPrincipal, "top:0.0px;left:0.0px;");
	
	return mainLayout;
    }

    private Component hazCabecera() {
	
	GridLayout grid = new GridLayout(3,1);
	grid.setStyleName("grid-cabecera");
	grid.setSpacing(true);
	grid.setMargin(true);
	grid.setWidth("100%");
	grid.setHeight("100%");
	
	Button botonSalir = new Button(StringsContainer.getString("tizona.principal.logout"));
	botonSalir.addListener(new ClickListener() {
	    @Override
	    public void buttonClick(ClickEvent event) {       
		doLogout();
	    }
	});
	grid.addComponent(botonSalir, 0, 0);
	grid.setComponentAlignment(botonSalir, new Alignment(Bits.ALIGNMENT_VERTICAL_CENTER
		| Bits.ALIGNMENT_LEFT));
	
	return grid;
	
    }
    
    private void doLogout() { 
	getApplication().close();
    }
    
}
