package es.guzman.tizona.screen.main;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class TabBuscar extends CustomComponent {

    @AutoGenerated
    private VerticalLayout mainLayout;

    @AutoGenerated
    private HorizontalLayout horizontalLayout_2;

    @AutoGenerated
    private Table tabla;

    @AutoGenerated
    private HorizontalLayout horizontalLayout_1;

    @AutoGenerated
    private Button button_1;

    @AutoGenerated
    private TextField textField_1;

    @AutoGenerated
    private Label label_1;

    private TabsContainer parent;

    /**
     * The constructor should first build the main layout, set the
     * composition root and then do any custom initialization.
     *
     * The constructor will not be automatically regenerated by the
     * visual editor.
     */
    public TabBuscar(TabsContainer t) {
	buildMainLayout();
	setCompositionRoot(mainLayout);
	
	this.parent = t;

	mainLayout.setSizeFull();
	mainLayout.addComponent(new Label("busca!"));
    }

    @AutoGenerated
    private VerticalLayout buildMainLayout() {
	// common part: create layout
	mainLayout = new VerticalLayout();
	mainLayout.setImmediate(false);
	mainLayout.setWidth("100%");
	mainLayout.setHeight("100%");
	mainLayout.setMargin(false);
	mainLayout.setSpacing(true);
	
	// top-level component properties
	setWidth("100.0%");
	setHeight("100.0%");
	
	// horizontalLayout_1
	horizontalLayout_1 = buildHorizontalLayout_1();
	mainLayout.addComponent(horizontalLayout_1);
	mainLayout.setComponentAlignment(horizontalLayout_1, new Alignment(20));
	
	// horizontalLayout_2
	horizontalLayout_2 = buildHorizontalLayout_2();
	mainLayout.addComponent(horizontalLayout_2);
	mainLayout.setExpandRatio(horizontalLayout_2, 1.0f);
	
	return mainLayout;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_1() {
	// common part: create layout
	horizontalLayout_1 = new HorizontalLayout();
	horizontalLayout_1.setImmediate(false);
	horizontalLayout_1.setWidth("-1px");
	horizontalLayout_1.setHeight("60px");
	horizontalLayout_1.setMargin(true);
	horizontalLayout_1.setSpacing(true);
	
	// label_1
	label_1 = new Label();
	label_1.setImmediate(false);
	label_1.setWidth("-1px");
	label_1.setHeight("-1px");
	label_1.setValue("Label");
	horizontalLayout_1.addComponent(label_1);
	
	// textField_1
	textField_1 = new TextField();
	textField_1.setImmediate(false);
	textField_1.setWidth("-1px");
	textField_1.setHeight("-1px");
	textField_1.setSecret(false);
	horizontalLayout_1.addComponent(textField_1);
	
	// button_1
	button_1 = new Button();
	button_1.setCaption("Button");
	button_1.setImmediate(true);
	button_1.setWidth("-1px");
	button_1.setHeight("-1px");
	horizontalLayout_1.addComponent(button_1);
	
	return horizontalLayout_1;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_2() {
	// common part: create layout
	horizontalLayout_2 = new HorizontalLayout();
	horizontalLayout_2.setImmediate(false);
	horizontalLayout_2.setWidth("100.0%");
	horizontalLayout_2.setHeight("100.0%");
	horizontalLayout_2.setMargin(false);
	
	// tabla
	tabla = new Table();
	tabla.setImmediate(false);
	tabla.setWidth("100.0%");
	tabla.setHeight("100.0%");
	horizontalLayout_2.addComponent(tabla);
	horizontalLayout_2.setExpandRatio(tabla, 1.0f);
	
	return horizontalLayout_2;
    }

}
