package es.guzman.tizona.screen.main;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;

public class TabBuscar extends CustomComponent {

    @AutoGenerated
    private VerticalLayout mainLayout;
    
    private TabsContainer parent;

    /**
     * The constructor should first build the main layout, set the
     * composition root and then do any custom initialization.
     *
     * The constructor will not be automatically regenerated by the
     * visual editor.
     */
    public TabBuscar(TabsContainer t) {
	buildMainLayout();
	setCompositionRoot(mainLayout);
	
	this.parent = t;

	mainLayout.setSizeFull();
	mainLayout.addComponent(new Label("busca!"));
    }

    @AutoGenerated
    private void buildMainLayout() {
	// the main layout and components will be created here
	mainLayout = new VerticalLayout();
    }

}
