package es.guzman.tizona.screen.main;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

import es.guzman.tizona.common.StringsContainer;

public class TabBuscar extends CustomComponent {

    @AutoGenerated
    private VerticalLayout mainLayout;

    @AutoGenerated
    private HorizontalLayout horizontalLayout_2;

    @AutoGenerated
    private Table tabla;

    @AutoGenerated
    private HorizontalLayout horizontalLayout_1;

    @AutoGenerated
    private Button buttonBuscar;

    @AutoGenerated
    private TextField textoBusqueda;

    private TabsContainer parent;

    /**
     * The constructor should first build the main layout, set the
     * composition root and then do any custom initialization.
     *
     * The constructor will not be automatically regenerated by the
     * visual editor.
     */
    public TabBuscar(TabsContainer t) {
	buildMainLayout();
	setCompositionRoot(mainLayout);
	
	this.parent = t;

	mainLayout.setSizeFull();
	
	// Ocultar la tabla en principio
	tabla.setVisible(false);
	
    }

    @AutoGenerated
    private VerticalLayout buildMainLayout() {
	// common part: create layout
	mainLayout = new VerticalLayout();
	mainLayout.setImmediate(false);
	mainLayout.setWidth("100%");
	mainLayout.setHeight("100%");
	mainLayout.setMargin(false);
	mainLayout.setSpacing(true);
	
	// top-level component properties
	setWidth("100.0%");
	setHeight("100.0%");
	
	// horizontalLayout_1
	horizontalLayout_1 = buildHorizontalLayout_1();
	mainLayout.addComponent(horizontalLayout_1);
	mainLayout.setComponentAlignment(horizontalLayout_1, new Alignment(20));
	
	// horizontalLayout_2
	horizontalLayout_2 = buildHorizontalLayout_2();
	mainLayout.addComponent(horizontalLayout_2);
	mainLayout.setExpandRatio(horizontalLayout_2, 1.0f);
	
	return mainLayout;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_1() {
	// common part: create layout
	horizontalLayout_1 = new HorizontalLayout();
	horizontalLayout_1.setImmediate(false);
	horizontalLayout_1.setWidth("-1px");
	horizontalLayout_1.setHeight("60px");
	horizontalLayout_1.setMargin(true);
	horizontalLayout_1.setSpacing(true);
	
	// textField_1
	textoBusqueda = new TextField();
	textoBusqueda.setImmediate(false);
	textoBusqueda.setWidth("-1px");
	textoBusqueda.setHeight("-1px");
	textoBusqueda.setSecret(false);
	horizontalLayout_1.addComponent(textoBusqueda);
	
	// button_1
	buttonBuscar = new Button();
	buttonBuscar.setCaption(StringsContainer.getString("tizona.principal.tabs.buscar.boton"));
	buttonBuscar.setImmediate(true);
	buttonBuscar.setWidth("-1px");
	buttonBuscar.setHeight("-1px");
	buttonBuscar.addListener(new ClickListener() {
	    
	    @Override
	    public void buttonClick(ClickEvent event) {
		doBuscar();
	    }
	});
	horizontalLayout_1.addComponent(buttonBuscar);
	
	return horizontalLayout_1;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_2() {
	// common part: create layout
	horizontalLayout_2 = new HorizontalLayout();
	horizontalLayout_2.setImmediate(false);
	horizontalLayout_2.setWidth("100.0%");
	horizontalLayout_2.setHeight("100.0%");
	horizontalLayout_2.setMargin(false);
	
	// tabla
	tabla = new Table();
	tabla.setImmediate(false);
	tabla.setWidth("100.0%");
	tabla.setHeight("100.0%");
	horizontalLayout_2.addComponent(tabla);
	horizontalLayout_2.setExpandRatio(tabla, 1.0f);
	
	return horizontalLayout_2;
    }
    
    private void doBuscar() {
	tabla.setVisible(true);
    }

}
