package es.guzman.tizona.screen.main;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;

import es.horus.g2common.beans.ui.PrincipalBean;

public class TabPaciente extends CustomComponent {

    @AutoGenerated
    private VerticalLayout mainLayout;

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     * 
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */
    public TabPaciente(PrincipalBean bean) {
	buildMainLayout();
	setCompositionRoot(mainLayout);

	// TODO add user code here
	mainLayout.addComponent(new Label(bean.getNombre()));
    }

    @AutoGenerated
    private void buildMainLayout() {
	// the main layout and components will be created here
	mainLayout = new VerticalLayout();
    }

}
